name: drumly
description: "Light Up Your Beat"
version: 1.1.5+27

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_blue_plus: ^1.36.8
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  shared_preferences: ^2.3.3
  flex_color_picker: ^3.7.0
  url_launcher: ^6.3.1
  just_audio: ^0.10.5
  rxdart: ^0.28.0
  provider: ^6.1.5
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_analytics: ^12.0.4
  firebase_remote_config: ^6.1.2
  flutter_launcher_icons: ^0.14.3
  google_mobile_ads: ^7.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  youtube_player_flutter: ^9.1.1
  package_info_plus: ^9.0.0
  intl: ^0.20.2
  easy_localization: ^3.0.7+1
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0
  lottie: ^3.2.0
  confetti: ^0.8.0
  # Add Flame game engine
  flame: ^1.34.0

  flutter_localizations:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/draw/
    - assets/images/icons/
    - assets/sounds/
    - assets/langs/
    - assets/animation/

dependency_overrides:
  # Updated versions that support Java 21 and Android SDK 35
  path_provider_android: ^2.2.18
  webview_flutter_android: ^4.10.2
